package com.spacesofting.weshare.utils

import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.os.Build
import androidx.core.app.NotificationCompat
import androidx.work.Worker
import androidx.work.WorkerParameters
import com.spacesofting.weshare.R
import com.spacesofting.weshare.api.Api
import com.spacesofting.weshare.common.Settings
import com.spacesofting.weshare.mvp.Refrash
import io.reactivex.android.schedulers.AndroidSchedulers


class RefreshTokenWorker(context: Context, workerParams: WorkerParameters) : Worker(context, workerParams) {

    override fun doWork(): Result {
        createNotification("Background Task", "This notification is generated by workManager")
        return Result.success()
    }

     private fun createNotification(title: String, description: String) {

        val notificationManager =
            applicationContext.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val notificationChannel =
                NotificationChannel("101", "channel", NotificationManager.IMPORTANCE_DEFAULT)
            notificationManager.createNotificationChannel(notificationChannel)
            refreshed()
        }

        val notificationBuilder = NotificationCompat.Builder(applicationContext, "101")
            .setContentTitle(title)
            .setContentText(description)
            .setSmallIcon(R.drawable.ic_launcher)

        notificationManager.notify(1, notificationBuilder.build())

    }

    fun refreshed()
    {
        val validationToken = Settings.ValidationToken
        //todo autorize
        val token = validationToken?.let { Refrash(it) }
        token?.let {
            Api.Auth.getNewToken(it)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe ({ it->
                    Settings.AccessToken = it.accessToken
                    Settings.ValidationToken = it.rowrefreshTokenVersion
                    //  ApplicationWrapper.user = it.user!!
                    //todo тут кладем токен в сохранялки Settings

                }){
                    it
                    //todo 403

                    //  autorize(mail)
                }
        }
    }
}